// Code generated by "stringer -type=AreaSize"; DO NOT EDIT.

package gotown

import "fmt"

const _AreaSize_name = "HutCottageHouseTowerCastlePalaceHamletVillageTownCityNationStateEmpire"

var _AreaSize_index = [...]uint8{0, 3, 10, 15, 20, 26, 32, 38, 45, 49, 53, 64, 70}

func (i AreaSize) String() string {
	if i < 0 || i >= AreaSize(len(_AreaSize_index)-1) {
		return fmt.Sprintf("AreaSize(%d)", i)
	}
	return _AreaSize_name[_AreaSize_index[i]:_AreaSize_index[i+1]]
}
