version: '2'
services: 
  api: 
    build: .
    ports: 
      - "8003:8003"
    volumes:
      - .:/go/src/github.com/slabgorb/gotown
      - /tmp/gotown:/docroot
    links:
      - redis
  redis:
    image: "redis:alpine"
    ports: 
      - 6379

  frontend: 
    build: ./web
    volumes: 
      - /tmp/gotown:/app
      - ./web:/web




