// Code generated by "stringer -type=Size"; DO NOT EDIT.

package townomatic

import "fmt"

const _Size_name = "HutCottageHouseTowerCastlePalaceHamletVillageTownCityNationStateEmpire"

var _Size_index = [...]uint8{0, 3, 10, 15, 20, 26, 32, 38, 45, 49, 53, 64, 70}

func (i Size) String() string {
	if i < 0 || i >= Size(len(_Size_index)-1) {
		return fmt.Sprintf("Size(%d)", i)
	}
	return _Size_name[_Size_index[i]:_Size_index[i+1]]
}
