// Code generated by go-bindata.
// sources:
// textures/seamless-watercolor-1.png
// textures/seamless-watercolor-10.png
// textures/seamless-watercolor-11.png
// textures/seamless-watercolor-12.png
// textures/seamless-watercolor-2.png
// textures/seamless-watercolor-3.png
// textures/seamless-watercolor-4.png
// textures/seamless-watercolor-5.png
// textures/seamless-watercolor-6.png
// textures/seamless-watercolor-7.png
// textures/seamless-watercolor-8.png
// textures/seamless-watercolor-9.png
// DO NOT EDIT!

package draw

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// texturesSeamlessWatercolor1Png reads file data from disk. It returns an error on failure.
func texturesSeamlessWatercolor1Png() (*asset, error) {
	path := "/home/keith/go/src/github.com/slabgorb/gotown/map/draw/textures/seamless-watercolor-1.png"
	name := "textures/seamless-watercolor-1.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// texturesSeamlessWatercolor10Png reads file data from disk. It returns an error on failure.
func texturesSeamlessWatercolor10Png() (*asset, error) {
	path := "/home/keith/go/src/github.com/slabgorb/gotown/map/draw/textures/seamless-watercolor-10.png"
	name := "textures/seamless-watercolor-10.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// texturesSeamlessWatercolor11Png reads file data from disk. It returns an error on failure.
func texturesSeamlessWatercolor11Png() (*asset, error) {
	path := "/home/keith/go/src/github.com/slabgorb/gotown/map/draw/textures/seamless-watercolor-11.png"
	name := "textures/seamless-watercolor-11.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// texturesSeamlessWatercolor12Png reads file data from disk. It returns an error on failure.
func texturesSeamlessWatercolor12Png() (*asset, error) {
	path := "/home/keith/go/src/github.com/slabgorb/gotown/map/draw/textures/seamless-watercolor-12.png"
	name := "textures/seamless-watercolor-12.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// texturesSeamlessWatercolor2Png reads file data from disk. It returns an error on failure.
func texturesSeamlessWatercolor2Png() (*asset, error) {
	path := "/home/keith/go/src/github.com/slabgorb/gotown/map/draw/textures/seamless-watercolor-2.png"
	name := "textures/seamless-watercolor-2.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// texturesSeamlessWatercolor3Png reads file data from disk. It returns an error on failure.
func texturesSeamlessWatercolor3Png() (*asset, error) {
	path := "/home/keith/go/src/github.com/slabgorb/gotown/map/draw/textures/seamless-watercolor-3.png"
	name := "textures/seamless-watercolor-3.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// texturesSeamlessWatercolor4Png reads file data from disk. It returns an error on failure.
func texturesSeamlessWatercolor4Png() (*asset, error) {
	path := "/home/keith/go/src/github.com/slabgorb/gotown/map/draw/textures/seamless-watercolor-4.png"
	name := "textures/seamless-watercolor-4.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// texturesSeamlessWatercolor5Png reads file data from disk. It returns an error on failure.
func texturesSeamlessWatercolor5Png() (*asset, error) {
	path := "/home/keith/go/src/github.com/slabgorb/gotown/map/draw/textures/seamless-watercolor-5.png"
	name := "textures/seamless-watercolor-5.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// texturesSeamlessWatercolor6Png reads file data from disk. It returns an error on failure.
func texturesSeamlessWatercolor6Png() (*asset, error) {
	path := "/home/keith/go/src/github.com/slabgorb/gotown/map/draw/textures/seamless-watercolor-6.png"
	name := "textures/seamless-watercolor-6.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// texturesSeamlessWatercolor7Png reads file data from disk. It returns an error on failure.
func texturesSeamlessWatercolor7Png() (*asset, error) {
	path := "/home/keith/go/src/github.com/slabgorb/gotown/map/draw/textures/seamless-watercolor-7.png"
	name := "textures/seamless-watercolor-7.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// texturesSeamlessWatercolor8Png reads file data from disk. It returns an error on failure.
func texturesSeamlessWatercolor8Png() (*asset, error) {
	path := "/home/keith/go/src/github.com/slabgorb/gotown/map/draw/textures/seamless-watercolor-8.png"
	name := "textures/seamless-watercolor-8.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// texturesSeamlessWatercolor9Png reads file data from disk. It returns an error on failure.
func texturesSeamlessWatercolor9Png() (*asset, error) {
	path := "/home/keith/go/src/github.com/slabgorb/gotown/map/draw/textures/seamless-watercolor-9.png"
	name := "textures/seamless-watercolor-9.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"textures/seamless-watercolor-1.png": texturesSeamlessWatercolor1Png,
	"textures/seamless-watercolor-10.png": texturesSeamlessWatercolor10Png,
	"textures/seamless-watercolor-11.png": texturesSeamlessWatercolor11Png,
	"textures/seamless-watercolor-12.png": texturesSeamlessWatercolor12Png,
	"textures/seamless-watercolor-2.png": texturesSeamlessWatercolor2Png,
	"textures/seamless-watercolor-3.png": texturesSeamlessWatercolor3Png,
	"textures/seamless-watercolor-4.png": texturesSeamlessWatercolor4Png,
	"textures/seamless-watercolor-5.png": texturesSeamlessWatercolor5Png,
	"textures/seamless-watercolor-6.png": texturesSeamlessWatercolor6Png,
	"textures/seamless-watercolor-7.png": texturesSeamlessWatercolor7Png,
	"textures/seamless-watercolor-8.png": texturesSeamlessWatercolor8Png,
	"textures/seamless-watercolor-9.png": texturesSeamlessWatercolor9Png,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"textures": &bintree{nil, map[string]*bintree{
		"seamless-watercolor-1.png": &bintree{texturesSeamlessWatercolor1Png, map[string]*bintree{}},
		"seamless-watercolor-10.png": &bintree{texturesSeamlessWatercolor10Png, map[string]*bintree{}},
		"seamless-watercolor-11.png": &bintree{texturesSeamlessWatercolor11Png, map[string]*bintree{}},
		"seamless-watercolor-12.png": &bintree{texturesSeamlessWatercolor12Png, map[string]*bintree{}},
		"seamless-watercolor-2.png": &bintree{texturesSeamlessWatercolor2Png, map[string]*bintree{}},
		"seamless-watercolor-3.png": &bintree{texturesSeamlessWatercolor3Png, map[string]*bintree{}},
		"seamless-watercolor-4.png": &bintree{texturesSeamlessWatercolor4Png, map[string]*bintree{}},
		"seamless-watercolor-5.png": &bintree{texturesSeamlessWatercolor5Png, map[string]*bintree{}},
		"seamless-watercolor-6.png": &bintree{texturesSeamlessWatercolor6Png, map[string]*bintree{}},
		"seamless-watercolor-7.png": &bintree{texturesSeamlessWatercolor7Png, map[string]*bintree{}},
		"seamless-watercolor-8.png": &bintree{texturesSeamlessWatercolor8Png, map[string]*bintree{}},
		"seamless-watercolor-9.png": &bintree{texturesSeamlessWatercolor9Png, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

