export const SELECT_SPECIES = 'SELECT_SPECIES';
export const RECEIVE_SPECIES = 'RECEIVE_SPECIES';
export const REQUEST_SPECIES = 'REQUEST_SPECIES';
export const LIST_SPECIES_SUCCESS = 'LIST_SPECIES_SUCCESS';
export const LIST_CULTURES_SUCCESS = 'LIST_CULTURES_SUCCESS';
